name: build package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install dependencies
        run: |
          npm install
          npm run build
      
      - name: zip package
        run: |
          cd dist_electron
          powershell Compress-Archive -Path win-unpacked -DestinationPath dist.zip

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ldapmanager-win
          path: dist_electron/dist.zip
          retention-days: 2
      
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ldapmanager-win
          path: dist_electron/LdapManage-0.1.0-win.zip
          retention-days: 2
