name: releases package
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: |
          npm install

      - name: unit test
        run: |
          npm run test:coverage
      
      - name: build electron app
        run: |
          npm run build
      
      - name: create github releases
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name  }}
          release_name: ${{ github.ref_name  }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist_electron/LdapManage-${{github.ref_name }}-win-x64.zip
          asset_name: ldapmanager-win-unpacked.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS }}
      